// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/csi/conversation.proto
// </auto-generated>
// Original file comments:
// Copyright 2021-2025 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Csi {
  /// <summary>
  /// &lt;p>Endpoints of CSI service.&lt;/p>
  /// </summary>
  public static partial class Conversations
  {
    static readonly string __ServiceName = "ondewo.csi.Conversations";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.S2sPipeline> __Marshaller_ondewo_csi_S2sPipeline = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.S2sPipeline.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.S2sPipelineId> __Marshaller_ondewo_csi_S2sPipelineId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.S2sPipelineId.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.ListS2sPipelinesRequest> __Marshaller_ondewo_csi_ListS2sPipelinesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.ListS2sPipelinesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.ListS2sPipelinesResponse> __Marshaller_ondewo_csi_ListS2sPipelinesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.ListS2sPipelinesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.S2sStreamRequest> __Marshaller_ondewo_csi_S2sStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.S2sStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.S2sStreamResponse> __Marshaller_ondewo_csi_S2sStreamResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.S2sStreamResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.CheckUpstreamHealthResponse> __Marshaller_ondewo_csi_CheckUpstreamHealthResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.CheckUpstreamHealthResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.ControlStreamRequest> __Marshaller_ondewo_csi_ControlStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.ControlStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.ControlStreamResponse> __Marshaller_ondewo_csi_ControlStreamResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.ControlStreamResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.SetControlStatusRequest> __Marshaller_ondewo_csi_SetControlStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.SetControlStatusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Csi.SetControlStatusResponse> __Marshaller_ondewo_csi_SetControlStatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Csi.SetControlStatusResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateS2sPipeline = new grpc::Method<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateS2sPipeline",
        __Marshaller_ondewo_csi_S2sPipeline,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.S2sPipelineId, global::Ondewo.Csi.S2sPipeline> __Method_GetS2sPipeline = new grpc::Method<global::Ondewo.Csi.S2sPipelineId, global::Ondewo.Csi.S2sPipeline>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetS2sPipeline",
        __Marshaller_ondewo_csi_S2sPipelineId,
        __Marshaller_ondewo_csi_S2sPipeline);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateS2sPipeline = new grpc::Method<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateS2sPipeline",
        __Marshaller_ondewo_csi_S2sPipeline,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.S2sPipelineId, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteS2sPipeline = new grpc::Method<global::Ondewo.Csi.S2sPipelineId, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteS2sPipeline",
        __Marshaller_ondewo_csi_S2sPipelineId,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.ListS2sPipelinesRequest, global::Ondewo.Csi.ListS2sPipelinesResponse> __Method_ListS2sPipelines = new grpc::Method<global::Ondewo.Csi.ListS2sPipelinesRequest, global::Ondewo.Csi.ListS2sPipelinesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListS2sPipelines",
        __Marshaller_ondewo_csi_ListS2sPipelinesRequest,
        __Marshaller_ondewo_csi_ListS2sPipelinesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.S2sStreamRequest, global::Ondewo.Csi.S2sStreamResponse> __Method_S2sStream = new grpc::Method<global::Ondewo.Csi.S2sStreamRequest, global::Ondewo.Csi.S2sStreamResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "S2sStream",
        __Marshaller_ondewo_csi_S2sStreamRequest,
        __Marshaller_ondewo_csi_S2sStreamResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Ondewo.Csi.CheckUpstreamHealthResponse> __Method_CheckUpstreamHealth = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Ondewo.Csi.CheckUpstreamHealthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckUpstreamHealth",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ondewo_csi_CheckUpstreamHealthResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.ControlStreamRequest, global::Ondewo.Csi.ControlStreamResponse> __Method_GetControlStream = new grpc::Method<global::Ondewo.Csi.ControlStreamRequest, global::Ondewo.Csi.ControlStreamResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetControlStream",
        __Marshaller_ondewo_csi_ControlStreamRequest,
        __Marshaller_ondewo_csi_ControlStreamResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Csi.SetControlStatusRequest, global::Ondewo.Csi.SetControlStatusResponse> __Method_SetControlStatus = new grpc::Method<global::Ondewo.Csi.SetControlStatusRequest, global::Ondewo.Csi.SetControlStatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetControlStatus",
        __Marshaller_ondewo_csi_SetControlStatusRequest,
        __Marshaller_ondewo_csi_SetControlStatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Csi.ConversationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Conversations</summary>
    [grpc::BindServiceMethod(typeof(Conversations), "BindService")]
    public abstract partial class ConversationsBase
    {
      /// <summary>
      /// &lt;p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CreateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Retrieve the S2S pipeline with the ID specified in the request message.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }
      /// &lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Csi.S2sPipeline> GetS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Update the S2S pipeline specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "en",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>List all S2S pipelines of the server.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "pipelines": [
      ///     {
      ///       "id": "pizza",
      ///       "s2t_pipeline_id": "default_german",
      ///       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///       "nlu_language_code": "de",
      ///       "t2s_pipeline_id": "default_german"
      ///     }
      ///   ]
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Csi.ListS2sPipelinesResponse> ListS2sPipelines(global::Ondewo.Csi.ListS2sPipelinesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Processes a natural language query in audio format in a streaming fashion and returns structured, actionable data as a result.&lt;/p>
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task S2sStream(grpc::IAsyncStreamReader<global::Ondewo.Csi.S2sStreamRequest> requestStream, grpc::IServerStreamWriter<global::Ondewo.Csi.S2sStreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Check the health of S2T, NLU and T2S servers.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
      /// &lt;/pre>
      ///
      /// All upstreams healthy:
      /// &lt;samp>{}&lt;/samp>
      ///
      /// All upstreams unhealthy:
      /// &lt;samp>{
      ///   "s2t_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "nlu_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "t2s_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   }
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Csi.CheckUpstreamHealthResponse> CheckUpstreamHealth(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Get the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetControlStream(global::Ondewo.Csi.ControlStreamRequest request, grpc::IServerStreamWriter<global::Ondewo.Csi.ControlStreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Csi.SetControlStatusResponse> SetControlStatus(global::Ondewo.Csi.SetControlStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Conversations</summary>
    public partial class ConversationsClient : grpc::ClientBase<ConversationsClient>
    {
      /// <summary>Creates a new client for Conversations</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ConversationsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Conversations that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ConversationsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ConversationsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ConversationsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// &lt;p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateS2sPipeline(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CreateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateS2sPipelineAsync(global::Ondewo.Csi.S2sPipeline request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateS2sPipelineAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Create the S2S pipeline specified in the request message. The pipeline with the specified ID must not exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.CreateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CreateS2sPipelineAsync(global::Ondewo.Csi.S2sPipeline request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Retrieve the S2S pipeline with the ID specified in the request message.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }
      /// &lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.S2sPipeline GetS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetS2sPipeline(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Retrieve the S2S pipeline with the ID specified in the request message.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }
      /// &lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.S2sPipeline GetS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Retrieve the S2S pipeline with the ID specified in the request message.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }
      /// &lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.S2sPipeline> GetS2sPipelineAsync(global::Ondewo.Csi.S2sPipelineId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetS2sPipelineAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Retrieve the S2S pipeline with the ID specified in the request message.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.GetS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "de",
      ///   "t2s_pipeline_id": "default_german"
      /// }
      /// &lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.S2sPipeline> GetS2sPipelineAsync(global::Ondewo.Csi.S2sPipelineId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Update the S2S pipeline specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "en",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateS2sPipeline(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Update the S2S pipeline specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "en",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateS2sPipeline(global::Ondewo.Csi.S2sPipeline request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Update the S2S pipeline specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "en",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateS2sPipelineAsync(global::Ondewo.Csi.S2sPipeline request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateS2sPipelineAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Update the S2S pipeline specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{
      ///   "id": "pizza",
      ///   "s2t_pipeline_id": "default_german",
      ///   "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///   "nlu_language_code": "en",
      ///   "t2s_pipeline_id": "default_german"
      /// }' localhost:50051 ondewo.csi.Conversations.UpdateS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateS2sPipelineAsync(global::Ondewo.Csi.S2sPipeline request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteS2sPipeline(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteS2sPipeline(global::Ondewo.Csi.S2sPipelineId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteS2sPipelineAsync(global::Ondewo.Csi.S2sPipelineId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteS2sPipelineAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Delete the S2S pipeline with the ID specified in the request message. The pipeline must exist.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext -d '{"id": "pizza"}' localhost:50051 ondewo.csi.Conversations.DeleteS2sPipeline
      /// &lt;/pre>
      /// &lt;samp>{}&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteS2sPipelineAsync(global::Ondewo.Csi.S2sPipelineId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteS2sPipeline, null, options, request);
      }
      /// <summary>
      /// &lt;p>List all S2S pipelines of the server.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "pipelines": [
      ///     {
      ///       "id": "pizza",
      ///       "s2t_pipeline_id": "default_german",
      ///       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///       "nlu_language_code": "de",
      ///       "t2s_pipeline_id": "default_german"
      ///     }
      ///   ]
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.ListS2sPipelinesResponse ListS2sPipelines(global::Ondewo.Csi.ListS2sPipelinesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListS2sPipelines(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>List all S2S pipelines of the server.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "pipelines": [
      ///     {
      ///       "id": "pizza",
      ///       "s2t_pipeline_id": "default_german",
      ///       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///       "nlu_language_code": "de",
      ///       "t2s_pipeline_id": "default_german"
      ///     }
      ///   ]
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.ListS2sPipelinesResponse ListS2sPipelines(global::Ondewo.Csi.ListS2sPipelinesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListS2sPipelines, null, options, request);
      }
      /// <summary>
      /// &lt;p>List all S2S pipelines of the server.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "pipelines": [
      ///     {
      ///       "id": "pizza",
      ///       "s2t_pipeline_id": "default_german",
      ///       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///       "nlu_language_code": "de",
      ///       "t2s_pipeline_id": "default_german"
      ///     }
      ///   ]
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.ListS2sPipelinesResponse> ListS2sPipelinesAsync(global::Ondewo.Csi.ListS2sPipelinesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListS2sPipelinesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>List all S2S pipelines of the server.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.ListS2sPipelines
      /// &lt;/pre>
      /// &lt;samp>{
      ///   "pipelines": [
      ///     {
      ///       "id": "pizza",
      ///       "s2t_pipeline_id": "default_german",
      ///       "nlu_project_id": "1f3425d2-41fd-4970-87e6-88e8e121bb49",
      ///       "nlu_language_code": "de",
      ///       "t2s_pipeline_id": "default_german"
      ///     }
      ///   ]
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.ListS2sPipelinesResponse> ListS2sPipelinesAsync(global::Ondewo.Csi.ListS2sPipelinesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListS2sPipelines, null, options, request);
      }
      /// <summary>
      /// &lt;p>Processes a natural language query in audio format in a streaming fashion and returns structured, actionable data as a result.&lt;/p>
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Ondewo.Csi.S2sStreamRequest, global::Ondewo.Csi.S2sStreamResponse> S2sStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return S2sStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Processes a natural language query in audio format in a streaming fashion and returns structured, actionable data as a result.&lt;/p>
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Ondewo.Csi.S2sStreamRequest, global::Ondewo.Csi.S2sStreamResponse> S2sStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_S2sStream, null, options);
      }
      /// <summary>
      /// &lt;p>Check the health of S2T, NLU and T2S servers.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
      /// &lt;/pre>
      ///
      /// All upstreams healthy:
      /// &lt;samp>{}&lt;/samp>
      ///
      /// All upstreams unhealthy:
      /// &lt;samp>{
      ///   "s2t_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "nlu_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "t2s_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   }
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.CheckUpstreamHealthResponse CheckUpstreamHealth(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckUpstreamHealth(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Check the health of S2T, NLU and T2S servers.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
      /// &lt;/pre>
      ///
      /// All upstreams healthy:
      /// &lt;samp>{}&lt;/samp>
      ///
      /// All upstreams unhealthy:
      /// &lt;samp>{
      ///   "s2t_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "nlu_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "t2s_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   }
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.CheckUpstreamHealthResponse CheckUpstreamHealth(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckUpstreamHealth, null, options, request);
      }
      /// <summary>
      /// &lt;p>Check the health of S2T, NLU and T2S servers.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
      /// &lt;/pre>
      ///
      /// All upstreams healthy:
      /// &lt;samp>{}&lt;/samp>
      ///
      /// All upstreams unhealthy:
      /// &lt;samp>{
      ///   "s2t_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "nlu_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "t2s_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   }
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.CheckUpstreamHealthResponse> CheckUpstreamHealthAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckUpstreamHealthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Check the health of S2T, NLU and T2S servers.&lt;/p>
      ///
      /// &lt;p>Examples:&lt;/p>
      ///
      /// &lt;pre>
      /// grpcurl -plaintext localhost:50051 ondewo.csi.Conversations.CheckUpstreamHealth
      /// &lt;/pre>
      ///
      /// All upstreams healthy:
      /// &lt;samp>{}&lt;/samp>
      ///
      /// All upstreams unhealthy:
      /// &lt;samp>{
      ///   "s2t_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "nlu_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   },
      ///   "t2s_status": {
      ///     "code": 14,
      ///     "message": "failed to connect to all addresses"
      ///   }
      /// }&lt;/samp>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.CheckUpstreamHealthResponse> CheckUpstreamHealthAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckUpstreamHealth, null, options, request);
      }
      /// <summary>
      /// &lt;p>Get the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Csi.ControlStreamResponse> GetControlStream(global::Ondewo.Csi.ControlStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetControlStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Get the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Csi.ControlStreamResponse> GetControlStream(global::Ondewo.Csi.ControlStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetControlStream, null, options, request);
      }
      /// <summary>
      /// &lt;p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.SetControlStatusResponse SetControlStatus(global::Ondewo.Csi.SetControlStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetControlStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Csi.SetControlStatusResponse SetControlStatus(global::Ondewo.Csi.SetControlStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetControlStatus, null, options, request);
      }
      /// <summary>
      /// &lt;p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.SetControlStatusResponse> SetControlStatusAsync(global::Ondewo.Csi.SetControlStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetControlStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Send a message on the control stream to control sip, t2s, s2t etc. during a conversation.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Csi.SetControlStatusResponse> SetControlStatusAsync(global::Ondewo.Csi.SetControlStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetControlStatus, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ConversationsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ConversationsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ConversationsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateS2sPipeline, serviceImpl.CreateS2sPipeline)
          .AddMethod(__Method_GetS2sPipeline, serviceImpl.GetS2sPipeline)
          .AddMethod(__Method_UpdateS2sPipeline, serviceImpl.UpdateS2sPipeline)
          .AddMethod(__Method_DeleteS2sPipeline, serviceImpl.DeleteS2sPipeline)
          .AddMethod(__Method_ListS2sPipelines, serviceImpl.ListS2sPipelines)
          .AddMethod(__Method_S2sStream, serviceImpl.S2sStream)
          .AddMethod(__Method_CheckUpstreamHealth, serviceImpl.CheckUpstreamHealth)
          .AddMethod(__Method_GetControlStream, serviceImpl.GetControlStream)
          .AddMethod(__Method_SetControlStatus, serviceImpl.SetControlStatus).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ConversationsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateS2sPipeline, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CreateS2sPipeline));
      serviceBinder.AddMethod(__Method_GetS2sPipeline, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.S2sPipelineId, global::Ondewo.Csi.S2sPipeline>(serviceImpl.GetS2sPipeline));
      serviceBinder.AddMethod(__Method_UpdateS2sPipeline, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.S2sPipeline, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateS2sPipeline));
      serviceBinder.AddMethod(__Method_DeleteS2sPipeline, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.S2sPipelineId, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteS2sPipeline));
      serviceBinder.AddMethod(__Method_ListS2sPipelines, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.ListS2sPipelinesRequest, global::Ondewo.Csi.ListS2sPipelinesResponse>(serviceImpl.ListS2sPipelines));
      serviceBinder.AddMethod(__Method_S2sStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Ondewo.Csi.S2sStreamRequest, global::Ondewo.Csi.S2sStreamResponse>(serviceImpl.S2sStream));
      serviceBinder.AddMethod(__Method_CheckUpstreamHealth, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Ondewo.Csi.CheckUpstreamHealthResponse>(serviceImpl.CheckUpstreamHealth));
      serviceBinder.AddMethod(__Method_GetControlStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ondewo.Csi.ControlStreamRequest, global::Ondewo.Csi.ControlStreamResponse>(serviceImpl.GetControlStream));
      serviceBinder.AddMethod(__Method_SetControlStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Csi.SetControlStatusRequest, global::Ondewo.Csi.SetControlStatusResponse>(serviceImpl.SetControlStatus));
    }

  }
}
#endregion
